version: '2'
services:
  files:
    image: dvranish/openvpn-files
    volumes:
      - ../conf:/data/conf
      - ../logs:/data/logs
  openvpn:
    image: dvranish/openvpn
    privileged: true
    restart: always
    env_file: ./openvpn.env
    ports:
      - 1194/udp:1194/udp
    volumes_from: 
      - files
