version: '2'
services:
  files:
    image: dvranish/openvpn-files
    volumes:
      - ../conf:/data/conf
      - ../keys:/data/keys
      - ../logs:/data/logs
  openvpn:
    image: dvranish/openvpn
    env_file: ./openvpn.vpn
    ports:
      - 1194/udp:1194/udp
    volumes_from: files